Erik/sprint3
ssw-555-summer-2019-group-aefs/GEDCOM pull request #14
Opened 2019-07-18 01:38 UTC by Erik-Bornako

- Addition of US29 and US30 (unit tested against us29.ged and us30.ged from Fran's branch)
- Separated unit test execution from main.py and into new file main_test.py
- Revised US 7&8 unit tests

2019-07-18 18:27 UTC, anthemwingate approved these changes

2019-07-20 23:24 UTC, fs412 requested changes
discussed w/ Erik

2019-07-21 21:08 UTC, sahlawat11 approved these changes

2019-07-21 21:55 UTC, fs412 approved these changes

2019-07-21 22:00 UTC, merged