Saransh/sprint3
ssw-555-summer-2019-group-aefs/GEDCOM pull request #17
Opened 2019-07-20 22:42 UTC by sahlawat11

2019-07-20 23:37 UTC, Erik-Bornako approved these changes
Good job!

2019-07-21 01:30 UTC, fs412 requested changes
Minor change discussed w/ Saransh

2019-07-21 02:21 UTC, anthemwingate approved these changes

2019-07-21 21:56 UTC, fs412 approved these changes

2019-07-21 22:16 UTC, merged